# coding: utf-8

"""
    A swagger API

    powered by Flasgger  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.oauth_api import OauthApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOauthApi(unittest.TestCase):
    """OauthApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.oauth_api.OauthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_oauth_callback_get(self):
        """Test case for oauth_callback_get

        Process callback from oauth provider  # noqa: E501
        """
        pass

    def test_oauth_signin_get(self):
        """Test case for oauth_signin_get

        Get oauth authorization redirect url for signup  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
