# coding: utf-8

"""
    A swagger API

    powered by Flasgger  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.deactivate_token import DeactivateToken  # noqa: E501
from swagger_client.rest import ApiException


class TestDeactivateToken(unittest.TestCase):
    """DeactivateToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeactivateToken(self):
        """Test DeactivateToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.deactivate_token.DeactivateToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
