# coding: utf-8

"""
    A swagger API

    powered by Flasgger  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_token import GetToken  # noqa: E501
from swagger_client.rest import ApiException


class TestGetToken(unittest.TestCase):
    """GetToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetToken(self):
        """Test GetToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_token.GetToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
