# coding: utf-8

"""
    A swagger API

    powered by Flasgger  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class HistoryModelResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'date_auth': 'str',
        'user_agent': 'str'
    }

    attribute_map = {
        'date_auth': 'date_auth',
        'user_agent': 'user_agent'
    }

    def __init__(self, date_auth=None, user_agent=None, _configuration=None):  # noqa: E501
        """HistoryModelResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._date_auth = None
        self._user_agent = None
        self.discriminator = None

        self.date_auth = date_auth
        self.user_agent = user_agent

    @property
    def date_auth(self):
        """Gets the date_auth of this HistoryModelResponse.  # noqa: E501


        :return: The date_auth of this HistoryModelResponse.  # noqa: E501
        :rtype: str
        """
        return self._date_auth

    @date_auth.setter
    def date_auth(self, date_auth):
        """Sets the date_auth of this HistoryModelResponse.


        :param date_auth: The date_auth of this HistoryModelResponse.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and date_auth is None:
            raise ValueError("Invalid value for `date_auth`, must not be `None`")  # noqa: E501

        self._date_auth = date_auth

    @property
    def user_agent(self):
        """Gets the user_agent of this HistoryModelResponse.  # noqa: E501


        :return: The user_agent of this HistoryModelResponse.  # noqa: E501
        :rtype: str
        """
        return self._user_agent

    @user_agent.setter
    def user_agent(self, user_agent):
        """Sets the user_agent of this HistoryModelResponse.


        :param user_agent: The user_agent of this HistoryModelResponse.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and user_agent is None:
            raise ValueError("Invalid value for `user_agent`, must not be `None`")  # noqa: E501

        self._user_agent = user_agent

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HistoryModelResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HistoryModelResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HistoryModelResponse):
            return True

        return self.to_dict() != other.to_dict()
